server:
  port: 8082

spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${hm.nacos.host}:${hm.nacos.port}

feign:
  okhttp:
    enabled: true

hm:
  db:
    host: ${hm.db.host}
    port: ${hm.db.port}
    pw: ${hm.db.pw}
    database: ${hm.db.database}
  swagger:
    title: "黑马商城购物车服务接口文档"
    package: com.hm.cart.controller
